### ISSUE TITLE
Vaadin UI is not saving in Redis

### ISSUE THREAD

**Issue by damontheimpulsive** [alejandro-du/vaadin-spring-session-redis#4]
Hi Alejandro,

I am using HawkBit (https://github.com/eclipse/hawkbit/tree/0.3.0M6)  which uses the vaadin 7.7.13 version.
I have implemented the same configuration as you mention 

Below are the dependencies I have added plus I have override RedisOperationsSessionRepository of Redis in my repo. Still, vaadinUI is not getting saved in Redis. Please, suggest something as it is very crucial for me to implement redis in hawkbit

<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>

		<dependency>
			<groupId>redis.clients</groupId>
			<artifactId>jedis</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.session</groupId>
			<artifactId>spring-session-data-redis</artifactId>
		</dependency>

		<dependency>
			<groupId>org.vaadin</groupId>
			<artifactId>spring-session-redis</artifactId>
			<version>1.0</version>
		</dependency>

**Comment by alejandro-du** [comment]
If you can provide a truly minimal project to reproduce the issue, that'd help. Otherwise, there's not much I can do.

**Comment by damontheimpulsive** [comment]
You can clone the git repo  from  this url (https://github.com/eclipse/hawkbit/tree/0.3.0M6) . It's an open source framework by Eclipse and make sure checkout 0.3.0M6 version then try to  add above depdency in pom.xml and run the application. When you login the application userName and password is admin. You will see VaadinUI object value is changing while saving in Redis.
Feel free to ask anything regarding more for code setup. It's a spring boot application

**Comment by alejandro-du** [comment]
Unfortunately, I don't have the time to learn projects as big as this one. If you can provide a minimal, reproducible example, I'll take a look. In the meantime, I'm closing this issue. Feel free to open it again when you can provide a "reprex". See https://stackoverflow.com/help/minimal-reproducible-example.
